#6. A partir del programa 5. Haz que se muestre por pantalla también la frase en el orden 
#inverso en que se han introducido las palabras.
var1=input("una paraula si us plau. :)  ")
var2=input("un altre. :)  ")
var3=input("un altre. :)  ")
var4=input("adivina una altre. ;) ")
var5=input("ultima: ")


print(var1+var2+var3+var4+var5)
print("   ")
print("   ")
print("   ")
print("que passa que no te sentit?")
print("   ")
print("   ")
print("   ")
print("et deixo una llista de paraules aleatories ----->")
print(f"{var1}, {var2}, {var3}, {var4}, {var5}. \_(·_·)_/ ")
print("   ")
print("   ")
print("un altre")
print("   ")
print("   ")
print("   ")
print(f"{var5}, {var4}, {var3}, {var3}, {var1}. \_($_$)_/ ")
